new commit

diff --git a/processes_and_signals/5-dont_stop_me_now b/processes_and_signals/5-dont_stop_me_now
--- a/processes_and_signals/5-dont_stop_me_now
+++ b/processes_and_signals/5-dont_stop_me_now
@@ -1,15 +1,12 @@
 #!/usr/bin/env bash
 # This script stops the 4-to_infinity_and_beyond process
 
-# Find the process ID (PID) of the 4-to_infinity_and_beyond process
-pid=$(pgrep "4-to_infinity_and_beyond")
+# Terminate the 4-to_infinity_and_beyond process
+pkill -f "4-to_infinity_and_beyond"
 
-# Check if the process is running
-if [ -n "$pid" ]; then
-  # Terminate the process
-  kill "$pid"
+# Check the exit status of the pkill command
+if [ $? -eq 0 ]; then
   echo "Terminated"
 else
   echo "Process not found"
 fi
-
